### ISSUE TITLE
GitHub Actions succeeds even though Scala-Steward fails

### ISSUE THREAD

**Issue by ryota0624** [scala-steward-org/scala-steward-action#169]
it occurred at invoke scala-steward (https://github.com/scala-steward-org/scala-steward-action/blob/master/src/main.ts#L36)

in my case, If GitHub returns status 403, steward raises an error.
but GitHub Actions job be succeeded.

By the way This 403 status response occurred because SSO for the GitHub Personal Access Token was not enabled in the repository that requires SSO.

**Comment by alejandrohdezma** [comment]
🤔 Certainly this is a problem, I've encountered it from time to time, but I don't know very well how to tackle it. @fthomas is there a way to tell if a clean Scala Steward run has failed?

**Comment by fthomas** [comment]
It should exit with status code 1 in case there was an error while working on one of the repos. If there are no errors, it exits with status code 0.

**Comment by alejandrohdezma** [comment]
And is there a way which repos have failed? If it is possible we could give that information to the user as action's results

**Comment by fthomas** [comment]
Right now only by carefully inspecting the logs. But we could write the failed repos at the end of a run to the console.

**Comment by fthomas** [comment]
I think I now understand why this happened. Prior to https://github.com/scala-steward-org/scala-steward/pull/1640, `RepoCacheAlg.checkCache` catched all errors, showed them in the logs but ignored them. Scala Steward only exited with a non-zero status if there was an error in `NurtureAlg.nurture`. https://github.com/scala-steward-org/scala-steward/pull/1640 changed this so that errors in both methods now lead to Scala Steward exiting with a non-zero status.

**Comment by alejandrohdezma** [comment]
Sorry @fthomas I totally missed your comment! The problem is that to get those changes we need a Scala Steward version to be published, since we use it via coursier's `launch`

**Comment by fthomas** [comment]
@alejandrohdezma Ok, I'll publish 0.7.0 soon. It seems that release-drafter stopped working after I moved the repository to this organization. I'm hoping I can convince release-drafter to update the release notes with all the changes since then. :crossed_fingers:

**Comment by fthomas** [comment]
0.7.0 is now available.

**Comment by alejandrohdezma** [comment]
Thanks!!
