### ISSUE TITLE
Install scalafmt with coursier

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward-action#187]
Since version 0.8.1 Scala Steward runs `scalafmt` after updating scalafmt to reformat sources automatically, see https://github.com/scala-steward-org/scala-steward/pull/1673. To support this, we should install scalafmt with `cs install scalafmt` before launching Scala Steward.

**Comment by alejandrohdezma** [comment]
Version `v2.9.0` has been published with this fix and the `v2` tag has been updated to point to it.
