### ISSUE TITLE
Enable to update artifacts that require credentials

### ISSUE THREAD

**Issue by rodobarcaaa** [scala-steward-org/scala-steward-action#209]
In the scala-steward [running.md](https://github.com/scala-steward-org/scala-steward/blob/master/docs/running.md#credentials-using-a-credentialssbt-file) docs, explain how to use your own credentials...

Can we enable this option with the action?

We were testing, several repositories and never updated the private libraries.

**Comment by alejandrohdezma** [comment]
Hi Rodolfo, that specific step can be done without needing to modify the action, you just need to add a new step to your workflow file (before running the Scala Steward action) that populates your `$HOME/.sbt/1.0/credentials.sbt` file with: `credentials += Credentials("Some Nexus Repository Manager", "my.artifact.repo.net", "admin", "admin123")` and Scala Steward should pick it up.

**Comment by rodobarcaaa** [comment]
Perfect, then I am gonna do it like this!

**Comment by rodobarcaaa** [comment]
@alejandrohdezma no work for me:
![image](https://user-images.githubusercontent.com/72995723/105710419-dba5b280-5ef5-11eb-9385-a2e1f36bc996.png)

I have more than 5 pending internal updates in this repo. Someone put this to work, I'm going to have to stop using the action and try running on a server with docker...

**Comment by fthomas** [comment]
@rodobarcaaa Can you try it again without restoring the workspace contents from the cache?

**Comment by alejandrohdezma** [comment]
@fthomas @rodobarcaaa that might be complicated, since the save/restore to/from cache is done by the action itself... and there is no possibility yet to disable it :(

**Comment by rodobarcaaa** [comment]
@fthomas I'm not sure how to disable that ... 

But I configured the action to a new repo, where there is no need to restore and I was not successful either.

![image](https://user-images.githubusercontent.com/72995723/105717508-fc263a80-5efe-11eb-85bf-1adf0a42e173.png)

Sorry if there is something that I am not understanding

**Comment by rodobarcaaa** [comment]
@fthomas, @alejandrohdezma any news about this? I tried running with docker and it doesn't work for me either...
![image](https://user-images.githubusercontent.com/72995723/111201941-121cb700-85a2-11eb-9950-af33adfcf0c9.png)

Keep only finding external libraries, exists some example of this?

**Comment by fthomas** [comment]
@rodobarcaaa check if `/opt/scala-steward/workspace/store/repo_cache/v1/github/BQN-UY/vaadin-app/repo_cache.json` contains your private libraries, the private resolver, and appropriate credentials. If they are all present, find a `versions.json` under `/opt/scala-steward/workspace/store/versions/` for any of your private libraries and check if it contains all available versions of that library or an error that indicates why they couldn't be fetched.

**Comment by rodobarcaaa** [comment]
@fthomas:
Resolvers and Credentials:  **OK**
![image](https://user-images.githubusercontent.com/72995723/111207290-31b6de00-85a8-11eb-9086-12bd85930ae5.png)

Libraries and Versions: **OK**
![image](https://user-images.githubusercontent.com/72995723/111207814-d76a4d00-85a8-11eb-9e1e-40eb058264b6.png)

At versions.json I found an error: **FAIL**
![image](https://user-images.githubusercontent.com/72995723/111208405-742cea80-85a9-11eb-8e84-757d70cd9074.png)

We are going to try to resolve that our Nexus 3 returns the maven-metadata.xml, it seems the error is there, thx very much friend

**Comment by alejandrohdezma** [comment]
So sorry @rodobarcaaa, I totally forgot about this issue.

In case it helps I have created #224 to allow disabling cache when `cache-ttl` is set to `0`.

**Comment by rodobarcaaa** [comment]
Thx, @alejandrohdezma, I'm going to close this problem and open it if at the end of everything I can't solve it, but everything seems to indicate that it is the fault of our Nexus 3.

Regards!

**Comment by rodobarcaaa** [comment]
@fthomas , @alejandrohdezma Once we solved the maven-metadata.xml in the nexus, everything worked perfectly

![image](https://user-images.githubusercontent.com/72995723/111484418-80818680-8714-11eb-8dd9-e86c9701dc16.png)

Thank you very much to both of you!

**Comment by fthomas** [comment]
That's great! Could you briefly explain how you fixed the issue in Nexus? It could be helpful for others who stumble on this too.

**Comment by rodobarcaaa** [comment]
Sure, wen start to use: 
[sbt-aether-deploy](https://github.com/arktekk/sbt-aether-deploy)

With config:
- overridePublishSettings
- overridePublishLocalSettings
or
- overridePublishBothSettings

Greetings, Rodo
