### ISSUE TITLE
Define multiple project subdirectories

### ISSUE THREAD

**Issue by dimisjim** [scala-steward-org/scala-steward-action#269]
Hey,

I have a repo that contains several sbt projects in multiple subdirectories. This action currently fails with:

```
plugins;stewardDependencies' exited with code 1
  /root/scala-steward/workspace/repos/myorg/myrepo doesn't appear to be an sbt project.
  If you want to start sbt anyway, run:
    /root/bin/sbt -sbt-create
```

Is it possible to make scala steward run in each one of the subdirectory independent projects?

Cheers, and thanks for the great project!

**Comment by alejandrohdezma** [comment]
Hey @dimisjim, this is resolved by Scala Steward itself, it's not specifically related with the action.

Nonetheless, [here](https://github.com/scala-steward-org/scala-steward/blob/master/docs/repo-specific-configuration.md#repository-specific-configuration) you can find the answer to your question.

> You can add <YOUR_REPO>/.scala-steward.conf to configure how Scala Steward updates your repository.
> 
> ```conf
> # It is possible to have multiple scala projects in a single repository.
> # In that case the folders containing the projects (build.sbt folders)
> # are specified using the buildRoots property. Note that the paths 
> # used there are relative and if the repo directory itself also contains
> # a build.sbt the dot can be used to specify it.
>
> # Default: ["."]
> buildRoots = [ ".", "subfolder/projectA" ]
>```

**Comment by dimisjim** [comment]
thanks, that did it!
