### ISSUE TITLE
Update releases

### ISSUE THREAD

**Issue by laughedelic** [scala-steward-org/scala-steward-action#282]
Hi! Could you update the tags to release the latest master as `v2.13.4`/`v2`? It includes the default Scala Steward version update.

**Comment by alejandrohdezma** [comment]
Hey @laughedelic, I don't know how I forgot doing that.

I've just released version `v2.13.4`/`v2`.

Thanks!

**Comment by laughedelic** [comment]
Thanks for the swift response!
