### ISSUE TITLE
Unable to install coursier

### ISSUE THREAD

**Issue by marcelocarlos** [scala-steward-org/scala-steward-action#29]
Hi,

First of all, thanks for building this GitHub action, this is great!

I've been having problems when running it though. I'm literally copying and pasting the example from https://github.com/scala-steward-org/scala-steward-action#usage and the action is failing with: `Unable to install coursier`

Here is the output of the step:

```
Launch scala-steward-org/scala-steward-action@v2
  with:
    github-token: ***
    scala-steward-version: 0.5.0-385-e5e4789c-SNAPSHOT
    ignore-opts-files: true
    sign-commits: false
✓ Connected to Maven Central
##[error] ✕ Unable to install coursier
```

Also tried fixing the version to `v2.1.0` and `v2.0.0` and it also fails.

Is anyone else experiencing the same?

**Comment by alejandrohdezma** [comment]
Hey @marcelocarlos, thanks for reporting this and I'm glad you find it useful :)

Can you enable debug mode in your Github Actions? This can be done by adding a secret to your repository named `ACTIONS_STEP_DEBUG` with the value `true`. And then re-run the action so we can get more information on why it cannot install Coursier?

Thank you!!

**Comment by marcelocarlos** [comment]
Of course, here it is the output:

```
##[debug]Evaluating condition for step: 'Launch Scala Steward'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Launch Scala Steward
##[debug]Loading inputs
##[debug]Evaluating: secrets.ADMIN_GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ADMIN_GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run scala-steward-org/scala-steward-action@v2
✓ Connected to Maven Central
##[debug]Downloading https://git.io/coursier-cli-linux
##[debug]Destination /home/runner/work/_temp/bbe1660a-10e9-49e6-bafc-38e02ca81513
##[debug]download complete
##[debug]EXDEV: cross-device link not permitted, rename '/home/runner/work/_temp/bbe1660a-10e9-49e6-bafc-38e02ca81513' -> '/home/runner/bin/cs'
##[error] ✕ Unable to install coursier
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Launch Scala Steward
```

**Comment by alejandrohdezma** [comment]
Is this being run on Github Action's runner or in a self-hosted runner? Also, is the action using `ubuntu-latest` as the running system or other OS?

**Comment by marcelocarlos** [comment]
> Is this being run on Github Action's runner or in a self-hosted runner? Also, is the action using ubuntu-latest as the running system or other OS?

Yes, tried `ubuntu-latest` (as in the example of the README) and `ubuntu-18.04` as well. Both cases running on Github Action's runner.

**Comment by alejandrohdezma** [comment]
I've created a simple test repository: [https://github.com/alejandrohdezma/test-scala-steward-action](https://github.com/alejandrohdezma/test-scala-steward-action), executed the action and it run fine.

Can you check if there is something different between your workflow and [this one](https://github.com/alejandrohdezma/test-scala-steward-action/blob/master/.github/workflows/scala-steward.yml)?

**Comment by marcelocarlos** [comment]
Thanks! I'm getting a 404, is that a private repo?

**Comment by alejandrohdezma** [comment]
Ups! Sorry! I forgot [gh](https://cli.github.com/) creates them as private by default. Should be public now

**Comment by marcelocarlos** [comment]
No worries. My workflow is exactly the same, except for the trigger (mine is on `push` while I'm testing it). Tried in a different repo, it also fails there.

It seems related with this line? https://github.com/scala-steward-org/scala-steward-action/blob/77cbae442ec3b1b259affee3c6b00a985f6a9d4f/src/coursier.ts#L20

**Comment by alejandrohdezma** [comment]
Yeah, that's what I think too. I've been trying to replicate this issue on different repositories (public/private, creating a new Github user...) without luck :(

I'll try to dig tomorrow into the actual error you posted from the debug logs to see I can get at least the root cause

**Comment by bpg** [comment]
I'm getting the same error as well: https://github.com/bpg/ss-gh-test/runs/695346873?check_suite_focus=true

I'm very new to GH Actions, but let me explain my train of thought, if it might help in investigation.
I think the difference in behavour between repos/builds could be due to slightly different GH Actions build agents, the way how project workspace is mounted inside the agent's container, etc... I'm a total nub in nodejs, but i think the `.mv` call is actually trying to rename the file. So if the source and target are on different volumes inside the container, the rename call will fails. According to the debug log above this is most likely what happens there.
So if we can switch from the "lame" `.mv` to actual move command (i.e. copy+delete, or just copy -- who cares what's left there :p ) that would be great!

**Comment by alejandrohdezma** [comment]
Thank you very much @bpg for that tip, I think that can be the solution! 🎉 

I just uploaded [a branch](https://github.com/scala-steward-org/scala-steward-action/tree/fix-mv) with the fix @bpg suggested.

You can use it by setting your "version" to commit hash:

```yaml
uses: scala-steward-org/scala-steward-action@07b63bf19f36bd08a077967ce592e872ee9ea171
```

I tried it in my own test repo and [it is working](https://github.com/alejandrohdezma/test-scala-steward-action/runs/695750374?check_suite_focus=true).

Can you both try with that version to check if that fixes the issue? Thanks! 😸

**Comment by marcelocarlos** [comment]
Thanks @alejandrohdezma 

I've just tried the new version, it is still failing unfortunately:

```
Run scala-steward-org/scala-steward-action@07b63bf19f36bd08a077967ce592e872ee9ea171
✓ Connected to Maven Central
##[debug]Downloading https://git.io/coursier-cli-linux
##[debug]Destination /home/runner/work/_temp/4e4e32f6-1342-4c09-9d4c-f8c7ff7b075e
##[debug]download complete
##[debug]EXDEV: cross-device link not permitted, rename '/home/runner/work/_temp/4e4e32f6-1342-4c09-9d4c-f8c7ff7b075e' -> '/home/runner/bin/cs'
##[error] ✕ Unable to install coursier
```

**Comment by marcelocarlos** [comment]
As an alternative, you could extract to a location and add that location to the PATH, so you don't need to move it to `/home/runner/bin`. It looks like this is what this action does: https://github.com/GoogleCloudPlatform/github-actions/blob/master/setup-gcloud/src/install-util.ts#L41

**Comment by alejandrohdezma** [comment]
My bad, I totally forgot to execute `npm run build` to re-generate the action'
s binaries. This is the actual hash for the `cp` + `rm` fix:

```yaml
uses: scala-steward-org/scala-steward-action@1dbeccd09b252b37a31750ad1cae96e13fa1a5ef
```

**Comment by marcelocarlos** [comment]
Great! That worked 🎉 
Thanks a lot!

**Comment by bpg** [comment]
Thanks @alejandrohdezma, that worked for me too!

**Comment by alejandrohdezma** [comment]
I'm really happy that worked :)

I just send a PR with the change, once tests passes I'll merge and re-publish `v2`.

Thank you both very much! 😸

**Comment by alejandrohdezma** [comment]
`v2` release has been updated to [`v2.1.1`](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.1.1)
