### ISSUE TITLE
Question: How to add credentials to work with private jar repository?

### ISSUE THREAD

**Issue by notxcain** [scala-steward-org/scala-steward-action#298]
Is there a way to pass credentials to private jar repository?

**Comment by michele-pinto-kensu** [comment]
> I will try that and create a PR to add this to the docs.

Hi, do you have any news? I have the same issue to solve. Thanks

**Comment by SirStoke** [comment]
I wasn't able to make `COURSIER_CREDENTIALS` or `SBT_CREDENTIALS` work, but setting up an `~/.m2/settings.xml` file in the step _before_ the scala steward one seems to work, like so:

```yaml
- name: Setup maven credentials
  id: maven-credentials
  env:
    MAVEN_CREDENTIALS_FILE: |
      <settings>
          <servers>
              <server>
                  <id>...</id>
                  <username>${{secrets.PRIVATE_REPO_USER}}</username>
                  <password>${{secrets.PRIVATE_REPO_PASSWORD}}</password>
              </server>
          </servers>
      </settings>
  run: |
    mkdir -p $HOME/.m2
    echo "$MAVEN_CREDENTIALS_FILE" > "$HOME/.m2/settings.xml"
- name: Run scala steward
...
```

**Comment by alejandrohdezma** [comment]
Does @SirStoke's comment fix the issue @notxcain?

**Comment by alejandrohdezma** [comment]
I'm closing this issue. @notxcain if the problem persists feel free to re-open or open a new one :)

**Comment by deepakmbr** [comment]
@alejandrohdezma The above proposed solution by @SirStoke does not work for me. Any ideas ? steward does not even look into our private artifactory.
