### ISSUE TITLE
become verified in the GitHub Marketplace

### ISSUE THREAD

**Issue by alek-w** [scala-steward-org/scala-steward-action#315]
Why Scala Steward Github Action is not certified by GitHub ?

**Comment by alejandrohdezma** [comment]
I believe the only actions certified by GitHub are those from GitHub "partner" companies.

<img width="746" alt="Screenshot 2022-01-04 at 16 20 06" src="https://user-images.githubusercontent.com/9027541/148081389-48f0275f-51dd-4dbc-90af-6291e597f0bd.png">

**Comment by alek-w** [comment]
could it help? @alejandrohdezma 
https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by alejandrohdezma** [comment]
🤔 cc @fthomas

**Comment by fthomas** [comment]
I just clicked "Request Verification" and the verification is now pending.

**Comment by fthomas** [comment]
The "Publisher Verification" page says now "Your publisher profile has been successfully verified.".
