### ISSUE TITLE
Need to handle rate limits

### ISSUE THREAD

**Issue by nadenf** [scala-steward-org/scala-steward-action#335]
If you use Scala Steward with a number of repos all running at the same time you may this rate limit:

```
You have exceeded a secondary rate limit and have been temporarily blocked from content creation
```

It's an identical issue to that seen [here](https://github.com/BetaHuhn/repo-file-sync-action/issues/126) and they have a fix that could be applied as well.

**Comment by exoego** [comment]
Thanks for reporting.
Let me close since I think this duplicates https://github.com/scala-steward-org/scala-steward/issues/2355 
You can subscribe the issue and get updates
