### ISSUE TITLE
New PRs not automatically superseding/closing old ones

### ISSUE THREAD

**Issue by armanbilge** [scala-steward-org/scala-steward-action#367]
Maybe the action doesn't support this the way the public instance did.

Example:
- https://github.com/gemini-hlsw/engage/pull/46
- https://github.com/gemini-hlsw/engage/pull/47

Thanks!

**Comment by alejandrohdezma** [comment]
Hi, how are you calling the action?

**Comment by armanbilge** [comment]
Thanks for fast response! Like this:
https://github.com/gemini-hlsw/lucuma-steward/blob/baebc61196bbc7704aa64da844820200fa0fc71e/.github/workflows/steward.yml#L22

**Comment by armanbilge** [comment]
Done: https://github.com/gemini-hlsw/lucuma-steward/runs/6729851036

**Comment by fthomas** [comment]
Here is the bit from the log where the workspace is restored from the cache:
```
  /usr/bin/tar --use-compress-program zstd -d -tf /home/runner/work/_temp/8ee0ac1e-da42-442c-a657-2a418ca42e14/cache.tzst -P
  ../../../scala-steward/workspace/
  ../../../scala-steward/workspace/store/
  ../../../scala-steward/workspace/store/repo_cache/
  ../../../scala-steward/workspace/store/repo_cache/v1/
  ../../../scala-steward/workspace/store/repo_cache/v1/github/
  ../../../scala-steward/workspace/store/repo_cache/v1/github/gemini-hlsw/
  ../../../scala-steward/workspace/store/repo_cache/v1/github/gemini-hlsw/lucuma-steward/
  ../../../scala-steward/workspace/store/repo_cache/v1/github/gemini-hlsw/lucuma-steward/repo_cache.json
```
There must be a `scala-steward/workspace/store/pull_requests/v2/github/gemini-hlsw/engage/pull_requests.json` in the cache for Scala Steward to know about previous PRs it should close. I've no idea why it doesn't exist.

**Comment by armanbilge** [comment]
Seems to be working fine in other orgs, e.g. https://github.com/http4s/hpack/pull/29. So there's something funky going on in that steward 🤔

**Comment by fthomas** [comment]
I've looked again at a few logs and it looks like that the workspace is only saved to the cache if Scala Steward exits with code 0. I think it should be saved even when Scala Steward exits with a non-zero code.

**Comment by armanbilge** [comment]
Aha, thanks you, that would explain what's different. So far seems that lucuma-steward hasn't been able to zero-exit.

**Comment by alejandrohdezma** [comment]
Oh! That's right! On it!

**Comment by alejandrohdezma** [comment]
`v2` & `v2.19.0` have been released including this change! Thank you all very much! ❤️
