### ISSUE TITLE
Missing `other-args`

### ISSUE THREAD

**Issue by leobenkel** [scala-steward-org/scala-steward-action#386]
The list of valid input (https://github.com/scala-steward-org/scala-steward-action/blob/master/action.yml) is missing `other-args`

**Comment by alejandrohdezma** [comment]
Hey @leobenkel, thank you very much for noticing this! I added the argument in #387

**Comment by alejandrohdezma** [comment]
`v2.22.0` and `v2` versions contain this change now 😸

**Comment by leobenkel** [comment]
nice ! Thank you @alejandrohdezma <3
