### ISSUE TITLE
Attempting to debug fails

### ISSUE THREAD

**Issue by jyrkih** [scala-steward-org/scala-steward-action#388]
Per readme, debugging should be enabled by setting repository secret:

> For this you must set the following secret in the repository that contains the workflow: `ACTIONS_STEP_DEBUG` to `true` (as stated in GitHub's documentation).

but actually, the code reads process environment, not repository secrets:
`const debug = 'ACTIONS_STEP_DEBUG' in process.env ? ['--java-opt', '-DLOG_LEVEL=TRACE', '-DROOT_LOG_LEVEL=TRACE'] : []`
which was added in #297.

When setting environment value ACTIONS_STEP_DEBUG=true, I get an error:

`Launching org.scala-steward:scala-steward-core_2.13:0.14.0
  Error: Unrecognized argument: -DROOT_LOG_LEVEL=TRACE
  ::endgroup::`

**Comment by alejandrohdezma** [comment]
Hey @jyrkih, sorry, I missed this.

That's weird, I'll check in Scala Steward's own code in case something has changed.

**Comment by alejandrohdezma** [comment]
@jyrkih `v2.23.0` has been released including this change.
