### ISSUE TITLE
File not found: dist/main.js

### ISSUE THREAD

**Issue by francisdb** [scala-steward-org/scala-steward-action#413]
Since last night our scala steward builds fail with

```
0s
Run scala-steward-org/scala-steward-action@v2
  with:
    repos-file: repos.md
    github-token: ***
    scala-steward-version: 0.16.0
    coursier-cli-url: https://git.io/coursier-cli-linux
    ignore-opts-files: true
    sign-commits: false
    timeout: 20min
    cache-ttl: 2hours
    github-api-url: https://api.github.com/
    repo-config: .github/.scala-steward.conf
Error: File not found: '/home/runner/work/_actions/scala-steward-org/scala-steward-action/v2/dist/main.js'
```

**Comment by francisdb** [comment]
probably related to #398

**Comment by ahjohannessen** [comment]
Also getting this [here](https://github.com/ahjohannessen/scala-steward-bot/actions/runs/3513191650).

**Comment by alejandrohdezma** [comment]
Thanks for raising this! It should be fixed now. The auto-release didn't work so I created a manual release without realising that we no longer have `dist` folder on the repo.

![](https://media.giphy.com/media/J7BzYsp7DLd4QZ3TAs/giphy.gif)

**Comment by francisdb** [comment]
No worries @alejandrohdezma 
Thanks for the quick fix. 👍

**Comment by ahjohannessen** [comment]
👍
