### ISSUE TITLE
Runner error: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by fmeriaux** [scala-steward-org/scala-steward-action#442]
Since this morning, our action (which run in self-hosted runner) has this error.

Error: 
> /home/runner/bin/cs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/bin/cs)

No problem yesterday. 

Maybe https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.39.0 ?

**Comment by alejandrohdezma** [comment]
Yeah, @ybasket brought it up yesterday in #440. It is a [known issue in Coursier](https://github.com/coursier/coursier/issues/2624). As mentioned [here](https://github.com/scala-steward-org/scala-steward-action/issues/440#issuecomment-1357842661), you can workaround it by setting your workflow to use v2.36.0 directly.

**Comment by fmeriaux** [comment]
Thanks

**Comment by alejandrohdezma** [comment]
Re-opening to keep track of this in case more people bumps into it

**Comment by adamw** [comment]
Updating `runs-on` from `ubuntu-20.04` to `ubuntu-22.04` fixed the problem for me. For reference here's my full config: https://github.com/softwaremill/tapir/blob/master/.github/workflows/scala-steward.yml

**Comment by alejandrohdezma** [comment]
Thanks Adam! I'll update the docs to reflect this 😊

**Comment by fmeriaux** [comment]
Thanks :) 
Unfortunately sometimes we have runner constraints (self-hosted)...

**Comment by andriygm** [comment]
Issue still seems to be present on my Debian 11 machine. Using v2.1.0-RC2 seems to work for now.

**Comment by xuwei-k** [comment]
I have same issue with self-hosted runner but solved with static-linked coursier 😃 

```diff
    - uses: scala-steward-org/scala-steward-action@a5515d934b0dfb84f0ff6432ecc2bd6a57d13e70 # v2.50.0
    - with:
+       coursier-cli-url: "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux-static.gz"
```

**Comment by alejandrohdezma** [comment]
That is great! Thanks @xuwei-k

@fmeriaux can you confirm if this works on your setup too?

**Comment by fmeriaux** [comment]
Hi,

I'll try it today and let you know.

For my information, what is the difference between the default link and the static link?

**Comment by alejandrohdezma** [comment]
I'm not an expert on this but I believe static binaries don't load external code (libraries are copied inside the binary). @xuwei-k can you confirm ☝🏼 is true?

**Comment by fmeriaux** [comment]
Re,

I tested it and it works, thanks !

Indeed I think it makes sense, I did not know this type of notation.

**Comment by alejandrohdezma** [comment]
Great, I'll close this now. Thank you very much everyone!
