### ISSUE TITLE
Steward treats a Mill subfolder as SBT

### ISSUE THREAD

**Issue by zhutmost** [scala-steward-org/scala-steward-action#475]
I have a repo, where a subfolder ‘hw’ is a Mill-based Scala project. I want to use Steward to manage its dependencies. 
However, the action log showed that Steward cannot process correctly. Looks that it regards it as a SBT project, so it cannot find any dependency.

Here is part of the action logs:
```
Launching scala-steward
2023-03-13 05:04:41,085 INFO   
    ____            _         ____  _                             _
   / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
   \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
    ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
   |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
   v0.23.0
   
  2023-03-13 05:04:43,221 INFO  Loaded 102 artifact migration(s)
  2023-03-13 05:04:43,444 INFO  Loaded 30 Scalafix migration(s)
  2023-03-13 05:04:43,589 INFO  Loaded 1 repo config(s)
  2023-03-13 05:04:44,008 INFO  Run self checks
  2023-03-13 05:04:44,109 INFO  Using git version 2.39.2
  2023-03-13 05:04:44,911 INFO  Using scalafix 0.10.4
  2023-03-13 05:04:45,852 INFO  Using scalafmt 3.7.2
  2023-03-13 05:04:46,830 INFO  Clean /home/runner/scala-steward/workspace/repos
  2023-03-13 05:04:46,864 INFO  ──────────── Steward zhutmost/beichen ────────────
  2023-03-13 05:04:46,869 INFO  Check cache of zhutmost/beichen
  2023-03-13 05:04:48,102 INFO  Clone zhutmost/beichen
  2023-03-13 05:04:49,236 INFO  Refresh cache of zhutmost/beichen
  2023-03-13 05:04:49,298 INFO  Get dependencies in . from sbt
  2023-03-13 05:05:33,295 INFO  Find updates for zhutmost/beichen
  2023-03-13 05:05:33,338 INFO  Found 0 updates
  2023-03-13 05:05:33,346 INFO  zhutmost/beichen is up-to-date
  2023-03-13 05:05:33,413 INFO  ──────────── Total time: Steward zhutmost/beichen: 46s 547ms ────────────
  2023-03-13 05:05:33,416 INFO  ──────────── Total time: run: 49s 409ms ────────────
```

Here `Get dependencies in . from sbt` should be `Get dependencies in ./hw from Mill`? :(

This is `.github/workflows/scala-steward.yml`:
```yaml
# Workflow to upgrade the Scala dependencies automatically

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Upgrade Scala Dependencies with Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest

    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_TOKEN }}
          author-name: "GitHub Action"
          author-email: "action@github.com"
```

This is `.github/.scala-steward.conf`:
```conf
buildRoots = [ "hw" ]
```

This is `hw/build.sc`:
```scala

import mill._
import scalalib._
import scalafmt._

object Deps {
  val scalaVersion = "2.13.10"

  val chiselVersion = "3.6.0-M2"
  val chisel        = ivy"edu.berkeley.cs::chisel3:$chiselVersion"
  val chiselPlugin  = ivy"edu.berkeley.cs:::chisel3-plugin:$chiselVersion"
  val chiselTest    = ivy"edu.berkeley.cs::chiseltest:0.5.5"
}

trait CommonModule extends ScalaModule with ScalafmtModule {
  override def scalaVersion = Deps.scalaVersion

  override def scalacOptions = T {
    super.scalacOptions() ++
      Agg(
        "-deprecation",
        "-feature",
        "-Xcheckinit",
        "-Xfatal-warnings",
        "-language:existentials",
        "-language:higherKinds",
        "-language:reflectiveCalls" // Required by Chisel
      )
  }

  override def ivyDeps             = Agg(Deps.chisel)
  override def scalacPluginIvyDeps = Agg(Deps.chiselPlugin)

  object test extends Tests {
    override def ivyDeps = super.ivyDeps() ++ Agg(Deps.chiselTest)
  }
}

object beichen extends CommonModule
```

**Comment by zhutmost** [comment]
I have used Steward in my many other repos. It works well.

The only difference is that these repos are standard Mill repos, and in the above repo, the Mill project is a subfolder

**Comment by fthomas** [comment]
It looks to me that the `.github/.scala-steward.conf` is not picked up. Are the files you listed above are all in the `zhutmost/beichen` repository? It should work if you move that file into the root of the repository.

**Comment by fthomas** [comment]
Does the action's log contain this line: `✓ Default Scala Steward configuration set to: .github/.scala-steward.conf`?

**Comment by zhutmost** [comment]
> It looks to me that the `.github/.scala-steward.conf` is not picked up. Are the files you listed above are all in the `zhutmost/beichen` repository? It should work if you move that file into the root of the repository.

@fthomas Thanks for your reply. That's my another question.

In this doc [repo-specific-configuration.md](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md), I need to put this conf file at the root of the repository (./.scala-steward.conf). But in the [action README](https://github.com/scala-steward-org/scala-steward-action/blob/master/README.md), the default path should be `.github/.scala-steward.conf`, i.e. put the conf file into .github folder.

**Comment by zhutmost** [comment]
> Does the action's log contain this line: `✓ Default Scala Steward configuration set to: .github/.scala-steward.conf`?

The complete log is attached. 
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/20497382/224634682-be83ae41-a162-4dea-a56f-04df24a03668.png">
 I guess not?

**Comment by alejandrohdezma** [comment]
Hey @zhutmost, you are missing a `checkout` option so the action can "see" the file

**Comment by alejandrohdezma** [comment]
See [this](https://github.com/alejandrohdezma/.github/blob/47e57de4073f228ff58a465c456d969420cdac41/.github/workflows/scala-steward.yml#L48-L49) for a example

**Comment by alejandrohdezma** [comment]
Is that file located at the root directory? Or inside `.github`? The file in `.github/.scala-steward.conf` is used by the `scala-steward-action` as the default configuration for any repository updated by that run. This means this is a `scala-steward-action` specific thing. On the other hand, the `.scala-steward.conf` in the root directory is used by Scala Steward itself. Since Scala Steward checkouts the repository it would use that file, but it will be completely oblivious to the `.github/.scala-steward.conf` file.

**Comment by zhutmost** [comment]
I put it in the `.github` folder now. Let me move it to the root and try again.

**Comment by zhutmost** [comment]
@alejandrohdezma Thank you. You are right. The conf file should be at the repo root. But it throw another error.

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/20497382/224740588-208c9c31-63cd-4973-9233-62f08abfb5de.png">

But the pull requests are still created correctly. I am not sure what the above error message refers to.

**Comment by zhutmost** [comment]
Looks something about scalafmt do not work well.

**Comment by alejandrohdezma** [comment]
It might be related to the scalamft version you have set in your `.scalafmt.conf` file

**Comment by zhutmost** [comment]
I specify the Scalafmt version 3.5.8 in `./hw/.scalafmt.conf`. It is in the Mill project subfolder. 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/20497382/224743305-079d1d39-d86d-4839-ac8e-50f05db464ce.png">

**Comment by fthomas** [comment]
That is a bug in Scala Steward. [`ScalafmtAlg#reformatChanged`](https://github.com/scala-steward-org/scala-steward/blob/070634501628558e00a7cd623c97bff1995e59e3/modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala#L55) works on the `Repo`-level but should work on the `BuildRoot`-level instead.

**Comment by zhutmost** [comment]
@fthomas Thanks a lot. My issue is solved.
Can we close this issue now?
