### ISSUE TITLE
Unable to install coursier - 502 error

### ISSUE THREAD

**Issue by tovbinm** [scala-steward-org/scala-steward-action#494]
<img width="973" alt="Screenshot 2023-05-01 at 09 09 30" src="https://user-images.githubusercontent.com/629845/235484801-64b36a3b-7cd3-419b-b47c-5e408a0a947f.png">

**Comment by alejandrohdezma** [comment]
Hey @tovbinm, is this still happening? It seems it was a temporary issue, since I just tried it on my repositories and it went fine

**Comment by tovbinm** [comment]
Works now. Thanks.
