### ISSUE TITLE
Scala steward action failed with OOM

### ISSUE THREAD

**Issue by manuzhang** [scala-steward-org/scala-steward-action#504]
My scala steward action constantly [failed with OOM](https://github.com/manuzhang/MyOvercast/actions/runs/5366854784/jobs/9736515375)

```
2023-06-25 00:29:12,590 ERROR Steward manuzhang/MyOvercast failed
  org.scalasteward.core.io.process$ProcessFailedException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1.
...
Error:  ZincCompiler.scala:230 msg.get() ## Exception when compiling 1932 sources to /home/runner/scala-steward/workspace/repos/manuzhang/MyOvercast/js/target/streams/_global/stImport/_global/streams/sources/s/std/target/scala-2.13/classes
  Error:  java.lang.OutOfMemoryError: Java heap space
  Error:  
  Error:              [project => frontend, ms => 924622]
  java.lang.OutOfMemoryError: Java heap space
  Error:  [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Java heap space
```

I've set [`ignore-opts-files: false`](https://github.com/manuzhang/MyOvercast/blob/main/.github/workflows/scala-steward.yml#L16) and `-XX:UseG1GC` in [.jvmopts](https://github.com/manuzhang/MyOvercast/blob/main/.jvmopts).

Is there anything else missing in my settings?

**Comment by alejandrohdezma** [comment]
Can you try creating an `.sbtopts` instead? It seems this is failing on SBT startup

**Comment by xerial** [comment]
Setting SBT_OPTS environment variable in GitHub Action worked for me:
```
    env:
      SBT_OPTS: -Xmx2G
```

Concrete example: 
https://github.com/xerial/scala-steward-repos/blob/e2d97bca90e2832c9d63900d495b326eaf162b3c/.github/workflows/scala-steward.yml#L12C1-L13C23

**Comment by manuzhang** [comment]
Thanks, it's finally working now.
