### ISSUE TITLE
Coursier error: Cannot find app org.scala-steward 

### ISSUE THREAD

**Issue by fmeriaux** [scala-steward-org/scala-steward-action#515]
Hello, since this morning we have the following error:

```
Launching org.scala-steward:scala-steward-core_2.13
  Error: Cannot find app org.scala-steward in channels io.get-coursier:apps, io.get-coursier:apps-contrib
Error:  ✕ Launching org.scala-steward:scala-steward-core_2.13 failed
``` 

Pre run info

> Run scala-steward-org/scala-steward-action@v2
> ✓ Connected to Maven Central
> ✓ Coursier installed, version: 2.1.5
> ✓ Scalafmt installed, version: 3.7.7
> ✓ Scalafix installed, version: 0.11.0
> ✓ scala-cli installed
> ✓ Mill installed, version: 0.10.9

**Comment by alejandrohdezma** [comment]
Hey @fmeriaux, thanks for reporting this. This should now be fixed in version [v2.59.0](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.59.0).
