### ISSUE TITLE
Enable usage on Github Enterprise

### ISSUE THREAD

**Issue by mzuehlke** [scala-steward-org/scala-steward-action#517]
I am trying to get this action running on an on-prem Github Enterprise. 
Till know I encountered 2 bugs that prevented it from working.

1.  Encode  newlines as "\n" in key
2. Github API URL is not used in `gitHubAppToken`

I am trying to come with a PR for this 😄

**Comment by alejandrohdezma** [comment]
For (2.) you need to provide the API URL to the function and then override `request` and provide the URL there:

```js
createAppAuth({
  appId: 1,
  privateKey: "-----BEGIN PRIVATE KEY-----\n...",
  request: request.defaults({
    baseUrl: "https://ghe.my-company.com/api/v3",
  }),
});
```

Reference: https://github.com/octokit/auth-app.js/#createappauthoptions-or-new-octokit-auth-

**Comment by mzuehlke** [comment]
Thanks for the hint, I found exactly the same snippet and with that I got it working 😄 
I have to tidy the code a bit before creating a PR.
