### ISSUE TITLE
Can one steward update multiple orgs

### ISSUE THREAD

**Issue by mzuehlke** [scala-steward-org/scala-steward-action#518]
I am trying to setup steward in on-prem Github and I am not sure if from the permission it is even possible to have one scala-steward that using the `repos.md` file updates repos in multiple orgs ?

Till now it only work in the repo from which  I have taken the `github-app-installation-id`

**Comment by alejandrohdezma** [comment]
It should be possible if you don't provide the installation ID and manually provide a token that has permission for creating PRs in repositories in all organizations. If you want to use the App's token it won't work (afaik) since it can only be generated per-installation.

**Comment by mzuehlke** [comment]
Found this out by trial and error 😄 
But having one steward instance per org seems to be good idea, so each one is smaller and each team can take care of their own.
Thx
