### ISSUE TITLE
Verify Github action creator

### ISSUE THREAD

**Issue by kiranbayram** [scala-steward-org/scala-steward-action#539]
I don't know how this is exactly done but it would be nice to have the GH action creator verified by GitHub. My company doesn't allow the usage otherwise :( Thank you in advance.

**Comment by fthomas** [comment]
I followed the above instructions and the Publisher Verification page now states:
> Your publisher profile has been successfully verified.

**Comment by kiranbayram** [comment]
Wow amazing, thank you folks a lot 🎉
