### ISSUE TITLE
Update cross-spawn to 7.0.5 or higher

### ISSUE THREAD

**Issue by aazimova** [scala-steward-org/scala-steward-action#662]
We detected that scala-steward-action uses cross-spawn lib lower then 7.0.5 , which introduces high  vulnerability as stated in https://security.snyk.io/vuln/SNYK-JS-CROSSSPAWN-8303230 .  This issue prevents us from using the action
Please update cross-spawn to 7.0.5 or higher
Scan results:
![Screenshot 2024-12-11 at 10 22 44 AM](https://github.com/user-attachments/assets/727019c0-37b1-4054-a0fb-bf68ce66566a)
 Thank you

**Comment by alejandrohdezma** [comment]
Hey @aazimova, just released [`v2.72.0`](https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.72.0) including that change.

**Comment by aazimova** [comment]
Thank you
